### ISSUE TITLE
problem with og:url and product:product_link

### ISSUE THREAD

**Issue by barco57** [torvista/zen-cart_Structured-Data#6]
This problem exists across this entire site, but the example page I will use is https://littlethingsofinterest.com/index.php?main_page=product_info&cPath=4&products_id=410
some of the FB structured data is below and you can see that the og:url and product:product_link have an extra amp; in them
`<meta property="og:url" content="https://littlethingsofinterest.com/index.php?main_page=product_info&amp;amp;products_id=410" />`

`<meta property="product:product_link" content="https://littlethingsofinterest.com/index.php?main_page=product_info&amp;amp;products_id=410" />`

Using addthis on the page for sharing but it never shares the product to FB it only wants to share the main domain and its logo rather than product info. Don't know if this is a result of the above issues or not. playing with https://developers.facebook.com/tools/debug/ to test gives me inconsistent results

**Comment by torvista** [comment]
ok. fixed.
